### PR TITLE
Add mime types sourced from IANA, nginx, apache

### LINKED ISSUE #28: is there a way to handle different mimetype for same extension
there are some extension has two mimetypes, such as：
rtf   application/rtf; text/rtf
sh   application/x-sh; text/x-sh

do we have a way to handle such a case or can we customize the buiitin mimetypes?

### PR DESCRIPTION
**Pull request by soyuka**
Source from https://github.com/jshttp/mime-db
IANA takes precedence

Extracted with https://gist.github.com/soyuka/b7e29d359b2c14c21bdead923c01cc81

### CODE REVIEW

**Comment by abonander** [comment]
While I don't consider the specific mime-types returned to be part of this crate's stable API, I'm wary of changing so many at once.  There are also quite a few that are being removed. Why?

This also does not fix #28 as I need to either refactor the API or introduce a new one to support returning multiple mime-types at once. I've edited your PR so that issue isn't closed by this being merged.

**Comment by soyuka** [comment]
I thought that by saying that the IANA source takes precedence over the others, it could be a fix for #28. Indeed, to handle multiple mime types per extensions it'd need a code change.

> There are also quite a few that are being removed. Why?

Could you give me one? I think that I just added them, nothing was removed. By the way the source of the data states:

> This is a database of all mime types. It consists of a single, public JSON file and does not include any logic, allowing it to remain as un-opinionated as possible with an API. It aggregates data from the following sources:
> http://www.iana.org/assignments/media-types/media-types.xhtml
> http://svn.apache.org/repos/asf/httpd/httpd/trunk/docs/conf/mime.types
> http://hg.nginx.org/nginx/raw-file/default/conf/mime.types

It's why there are so many changes, there where a bunch missing. What we could do also is restrict the types to the IANA source.

**Comment by abonander** [comment]
> Could you give me one? I think that I just added them, nothing was removed. By the way the source of the data states:

Just in the first handful of lines:

* `323`
* `3gp2`
* `aa`
* `aaf`
* `aax`
* `ac3`

**Comment by soyuka** [comment]
`ac3` has no registered extension in the database I used :|. `323` or `3gp2` aren't registered at the IANA for example.

**Comment by abonander** [comment]
I don't necessarily want to restrict this list to just what is in the IANA database. Covering as many extensions as possible with the best guesses available is really the goal, and many media types are declared informally or in obscure documents like old RFCs. I don't care about binary bloat as much as some people; if it really becomes an issue we could separate the list based on the source of the media type and let the user filter only IANA verified types via a Cargo feature or something.

**Comment by soyuka** [comment]
I fixed removal by combining the two data sources. Note that IANA types `aac` as `audio/x-aac` instead of `audio/aac` for example.

**Comment by abonander** [comment]
It is listed as `audio/aac` here: https://www.iana.org/assignments/media-types/media-types.xhtml#audio

**Comment by soyuka** [comment]
Oh my bad it's apache rules that specifies `x-`, good catch.

**Comment by abonander** [comment]
LGTM now, sorry for the delay.

**Comment by abonander** [comment]
Published as `2.0.0-alpha.6` and `1.8.6`.

**Comment by soyuka** [comment]
> LGTM now, sorry for the delay. 

No problem take all the time you want :). 

> Published as 2.0.0-alpha.6 and 1.8.6.

:+1: thanks!

**Pull request merged**
