### PR TITLE
Upgrade mime to 0.3

### PR DESCRIPTION
**Pull request by quininer**
:)

### CODE REVIEW

**Comment by abonander** [comment]
This is a breaking change which would require bumping `mime_guess` to version 2.0, which I'm hesitant to do unless there's a really compelling reason, like `mime` publishing a 1.0 release.

Honestly, I kinda screwed myself when I released 1.0 even though the crate's public dependencies (namely `mime`) had not yet reached 1.0 because I misunderstood one of the rules of Semver. By the time I realized my mistake it was too late to correct it.

**Comment by quininer** [comment]
I think you only need to publish 1.9.0 without having to publish 2.0.0.

http://semver.org/#what-should-i-do-if-i-update-my-own-dependencies-without-changing-the-public-api

**Comment by abonander** [comment]
No, because `mime::Mime` is part of the public API, so consumers of this crate will need to upgrade their `mime` as well, a breaking change.

**Comment by quininer** [comment]
Anyway, the current mime_guess can not work with mime 0.3. 
As a compromise, can publish 2.0.0-alpha?

**Comment by abonander** [comment]
That could be acceptable, but I don't want it to be in alpha for too long, so it might be a good idea to check with the `mime` maintainers to get a feel on when they might be planning to release their 1.0.

I've opened https://github.com/hyperium/mime/issues/52 so we'll see what comes up there.

**Comment by abonander** [comment]
I'll go ahead and merge this but first I want to create a branch for 1.x maintenance.

**Comment by quininer** [comment]
If you are going to publish 2.0, I would like unicase dependencies to be updated as well.

**Comment by abonander** [comment]
`unicase` isn't a public dependency so that can be upgraded before 2.0 as well.

**Comment by abonander** [comment]
Turns out that is blocked on `phf` upgrading to `unicase 2.0` first.

**Comment by quininer** [comment]
At present it seems to be impossible, it needs unicase to provide a `const fn`.

**Comment by abonander** [comment]
Yeah the change to `Unicase` was a little unfortunate for `phf`, hopefully they either implement a `const fn` or backtrack, because the performance from `phf` is too good to give up.

Sorry for the delay, merging this now.

**Comment by quininer** [comment]
you can publish it to crates.io?

**Comment by abonander** [comment]
Yeah, publishing now.

**Pull request merged**
