### PR TITLE
Add text/gemini

### PR DESCRIPTION
**Pull request by Xe**
See https://gemini.circumlunar.space/docs/specification.html section 5 for the description of this media type.

### CODE REVIEW

**Comment by abonander** [comment]
@Xe I see the media type description but I don't see where the file extensions are named.

**Comment by garritfra** [comment]
.gmi or .gemini are convention for gemini files. I'd love to see this merged, since we currently have to fallback to a custom implementation in our project.

**Comment by Alch-Emi** [comment]
I'd like to chip in a thought here too.  [The northstar project is similarly blocked on this](https://github.com/panicbit/northstar/issues/6).  I know .gmi isn't formally mentioned in the spec, but this has become a convention to the point of practically being a standard.  In fact, the standard itself is served from a .gmi file on the official gemini page

> gemini://gemini.circumlunar.space/docs/specification.gmi

as is most ever other page on that site.  Searching gus.guru, gemini's native search engine, for '.gmi' gives 8,755 results, and I'd also invite you to look at the search results for all pages served with a `text/gemini` extension, where you will find that almost all of the files served are served with a .gmi extension, and the ones that aren't are typically directories.  If you look up just about any gemini server, you'll find that directories are served with a text/gemini mime for index.gmi files, suggesting that these results too use .gmi as the extension for a gemini file

> gemini://gus.guru/search?.gmi

> gemini://gus.guru/search?content_type%3Atext/gemini

I know it's not official, but this is as close as it's ever going to get.  Projects are already using .gmi files everywhere, with no indication of changing anytime soon.

**Comment by panicbit** [comment]
Northstar isn't really blocked by this, I can manually test for a Gemini extension and then reach out to mime_guess.

Anyway, the [best practices document](https://gemini.circumlunar.space/docs/best-practices.html) section "Filenames" also mentions `.gmi` and `.gemini` regarding MIME type detection:
> Current Gemini servers seem to use .gmi or .gemini extensions for this purpose, and new servers are strongly encouraged to support one or both of these options instead of adding a new one to the mix.

**Pull request merged**
